change lambda url placeholder to main.js

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -64,7 +64,7 @@ jobs:
       run: |
         aws s3 cp role.txt s3://${{ secrets.AWS_S3_BUCKET}}/role.txt --cache-control no-store
     
-    - name: Apply Lambda function to html
+    - name: Apply Lambda function to js
       run: |
        # Get the URL from Terraform output
        URL=$(terraform output -raw function_url 2>&1 | \
@@ -73,11 +73,11 @@ jobs:
             tr -d '\n')
 
        echo "Lambda URL is: $URL"
-       # Replace the placeholder in index.html
-       sed -i "s|__LAMBDA_URL__|$URL|g" index.html
+       # Replace the placeholder in main.js
+       sed -i "s|__LAMBDA_URL__|$URL|g" assets/main.js
 
     - name: Show modified fetch line
-      run: grep "fetch(" index.html || echo "fetch line not found"
+      run: grep "fetch(" assets/main.js || echo "fetch line not found"
 
     - name: Upload index.html to S3
       run: |
